#!/bin/bash
# deploy.sh — Build and deploy to GitHub Pages
# Usage: ./deploy.sh
#
# Workflow:
#   1. Edit frontend/data.json with your plan data
#   2. Run ./deploy.sh
#   3. Site updates at https://otakgemuk.github.io/prop-firm-api/

set -e
cd "$(dirname "$0")"

echo "→ Generating static data from data.json..."
node -e "
  const data = require('./frontend/data.json');
  const plans = data.data || data;
  const ts = '// Auto-generated by deploy.sh — do not edit manually\n' +
    '// To update: edit data.json then run ./deploy.sh\n\n' +
    'export const STATIC_PLANS = ' + JSON.stringify(plans, null, 2) + ';\n';
  require('fs').writeFileSync('./frontend/src/lib/staticData.ts', ts);
  console.log('  ✓ Wrote ' + plans.length + ' plans to staticData.ts');
"

echo "→ Building frontend..."
cd frontend && npx vite build 2>&1 && cd ..

echo "→ Pushing to gh-pages..."
git add frontend/data.json frontend/src/lib/staticData.ts frontend/dist -f
git commit -m "Update data $(date +%Y-%m-%d)" 2>/dev/null || echo "  (no changes to commit)"
git branch -D gh-pages 2>/dev/null || true
git subtree split --prefix=frontend/dist --branch gh-pages
git remote set-url origin https://github.com/otakgemuk/prop-firm-api.git 2>/dev/null
git push origin gh-pages --force

echo ""
echo "✓ Deployed! Site will update in ~1 minute."
echo "  https://otakgemuk.github.io/prop-firm-api/"
